/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import MessageSystem.Message;
import Objects.DoctorRating;
import Objects.DoctorRatingsDatabase;
import Objects.UserDatabase;
import doctors.surgery.users.Doctor;
import doctors.surgery.users.Patient;
import doctors.surgery.users.SystemUser;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author jwood20
 */
public class AdminPortal extends javax.swing.JFrame {

    /**
     * Creates new form AdminPortal
     */
    UserDatabase userData = UserDatabase.getInstanceOfDatabase();
    DoctorRatingsDatabase ratingDatabase = DoctorRatingsDatabase.getInstanceOfDatabase();
    
    ArrayList<DoctorRating> docsRatings;
    
    public AdminPortal() {
        initComponents();
        
        jList_ratings.removeAll();
        
        //populate with DOCS
        Doctor testDoc1 = new Doctor("Bowditch");
        Doctor testDoc2 = new Doctor("Smith");
        Doctor testDoc3 = new Doctor("Jones");
        
        userData.addUser(testDoc1);
        userData.addUser(testDoc2);
        userData.addUser(testDoc3);
        
        DefaultListModel<String> docListModel = new DefaultListModel<>();
        
        for(Integer i = 0; i < userData.getNumberOfRoles("Doctor") ; i ++)
        {
            String tempString;
            tempString = userData.getListOfRoles("Doctor").get(i).getSurname();
            docListModel.addElement(tempString);
        }
        
        jList_Docs.setModel(docListModel);
        jList_pickDocReport.setModel(docListModel);
        
        
        //populate with ratings for docs
        //make some ratings
        DoctorRating testRate = new DoctorRating("Bowditch", 3, "Lots of hats");
        DoctorRating testRate2 = new DoctorRating("Smith", 2, "Bad magazines");
        DoctorRating testRate3 = new DoctorRating("Jones", 4, "Good lad");
        DoctorRating testRate4 = new DoctorRating("Bowditch", 5, "Friendly");
        DoctorRating testRate5 = new DoctorRating("Smith", 4, "Funny");
        DoctorRating testRate6 = new DoctorRating("Jones", 1, "Weird Hair");
        ratingDatabase.addNewRating(testRate);
        ratingDatabase.addNewRating(testRate2);
         ratingDatabase.addNewRating(testRate3);
         ratingDatabase.addNewRating(testRate4);
        ratingDatabase.addNewRating(testRate5);
         ratingDatabase.addNewRating(testRate6);
        
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        
        for(Integer i = 0; i < ratingDatabase.allRatings.size() ; i++)
        {
            String listText;
            listText = "Doctor " + ratingDatabase.allRatings.get(i).getDoctor().getSurname() + " : " + 
                    ratingDatabase.allRatings.get(i).getRateOutOfFive() + "/5 stars";
            listModel.addElement(listText);
        }
        jList_ratings.setModel(listModel);
        
        
    }
    
    public void sendRatingReport()
    {
        //SystemUser sender, SystemUser recipient, String message
        SystemUser sender = userData.getLoggedInUser();
        String docName = jList_pickDocReport.getSelectedValue();
        SystemUser recipient = userData.findDoctor(docName);
        String message = txt_report.getText();
        
        Message newMessage = new Message(sender, recipient, message, "Ratings report");
        recipient.sendMessage(newMessage);
    }
    
    
    
    public void updateRatingsList(String currentDoc)
    {
        docsRatings = ratingDatabase.getDocsRatingsSurname(currentDoc);
        
        DefaultListModel<String> docsListModel = new DefaultListModel<>();
        
        for(Integer i = 0; i < docsRatings.size() ; i++)
        {
            String listText;
            listText = docsRatings.get(i).getRateOutOfFive() + "/5 stars";
            docsListModel.addElement(listText);
        }
        jList_ratings.setModel(docsListModel);
        
        updateComments();
    }

    public void updateComments()
    {
        String newText = "";
        if(jList_ratings.getSelectedIndex() < 0)
        {
            newText = docsRatings.get(0).getComments();
        }
        else
        {
            newText = docsRatings.get(jList_ratings.getSelectedIndex()).getComments();
        }
        
        txt_comments.setText(newText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_ratings = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Docs = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_comments = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_report = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        btn_sendReport = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_pickDocReport = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Pick a Rating to View");

        jList_ratings.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jList_ratings.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_ratings.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_ratingsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_ratings);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Select a Doctor to view their ratings");

        jList_Docs.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jList_Docs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_Docs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_Docs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_DocsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList_Docs);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Comments");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel5.setText("VIEW DOCTOR RATINGS FOR YOUR SURGERY ");

        txt_comments.setEditable(false);
        txt_comments.setColumns(20);
        txt_comments.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txt_comments.setRows(5);
        jScrollPane2.setViewportView(txt_comments);

        jLabel1.setText("jLabel1");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel6.setText("GIVE FEEDBACK BASED ON RATINGS");

        txt_report.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jScrollPane5.setViewportView(txt_report);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Compose report to send to Doctor");

        btn_sendReport.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        btn_sendReport.setText("Send Report");
        btn_sendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendReportActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btn_sendReport, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(154, 154, 154)
                .addComponent(jLabel4)
                .addGap(168, 168, 168))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(180, 180, 180))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(245, 245, 245))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(btn_sendReport, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(72, 72, 72)))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(46, 46, 46)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sendReport, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );

        jTabbedPane1.addTab("Doctor Ratings", jLayeredPane1);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel9.setText("ADMINISTRATOR PORTAL ");

        jList_pickDocReport.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jList_pickDocReport.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "DOCS TO PICK FROM" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_pickDocReport.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jList_pickDocReport);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Select which Doctor to send report to");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(745, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jLabel9)
                            .addGap(533, 533, 533)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(454, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9)
                    .addGap(45, 45, 45)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_DocsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_DocsValueChanged
        // TODO add your handling code here:
        //CHANGE WHICH DOCTORS RATINGS TO VIEW

        updateRatingsList(jList_Docs.getSelectedValue());
    }//GEN-LAST:event_jList_DocsValueChanged

    private void jList_ratingsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_ratingsValueChanged
        // TODO add your handling code here:
        updateComments();
    }//GEN-LAST:event_jList_ratingsValueChanged

    private void btn_sendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendReportActionPerformed
        // TODO add your handling code here:
        sendRatingReport();
    }//GEN-LAST:event_btn_sendReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sendReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList_Docs;
    private javax.swing.JList<String> jList_pickDocReport;
    private javax.swing.JList<String> jList_ratings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txt_comments;
    private javax.swing.JTextPane txt_report;
    // End of variables declaration//GEN-END:variables
}
