/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Objects.Address;
import Objects.UserDatabase;
import doctors.surgery.users.Doctor;
import doctors.surgery.users.Patient;
import doctors.surgery.users.SystemUser;

/**
 *
 * @author jwood20
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    
   UserDatabase userDatabase;
    public Login() {
        initComponents();
        
        // set up database and add first person to database to login as
        userDatabase = UserDatabase.getInstanceOfDatabase();
        SystemUser testUser1 = new SystemUser("Administrator", userDatabase);
        Address newAdd = new Address(32, "Dorchester Lane", "Plymouth", "PL4 8LY");
        Patient testPatient = new Patient("Jane", "Doe", newAdd, 21, "Female");
        userDatabase.addUser(testUser1);
        userDatabase.addUser(testPatient);
        Doctor testDoc = new Doctor();
        userDatabase.addUser(testDoc);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_Pw = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        lbl_outputStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl_title.setText("LOG IN TO YOUR SURGERY PORTAL");
        lbl_title.setToolTipText("");

        txt_ID.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txt_ID.setText("<ID>");
        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });

        txt_Pw.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txt_Pw.setText("<Password>");

        btn_login.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        btn_login.setText("Log in ");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        lbl_outputStatus.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lbl_outputStatus.setText("-login status-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txt_Pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_outputStatus)
                    .addComponent(btn_login))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbl_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbl_title)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_outputStatus)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        // TRY AND LOGIN WITH GIVEN DETAILS
        
        
        
        String ID = txt_ID.getText();
        String pw = txt_Pw.getText();
        if(userDatabase.login(ID, pw))
        {
            lbl_outputStatus.setText("LOGGED IN"); 
            SystemUser thePat = (userDatabase.findUserWithID(ID));
            userDatabase.logInAsUser(thePat);
            
            System.out.println(thePat.getForename());
            System.out.println(userDatabase.loggedInUser.getForename());
            
            openRelevantPortal();
            
            
        }
        else
        {
            lbl_outputStatus.setText("ERROR"); 
        }
        
        
    }//GEN-LAST:event_btn_loginActionPerformed

    public void openRelevantPortal()
    {
        String ID_type = userDatabase.getLoggedInUser().getFirstLetterID();
        
        if(ID_type.equals("P"))
        {
            
            this.setVisible(false);
            new PatientPortal().setVisible(true);
        }
        else if(ID_type.equals("A"))
        {
            this.setVisible(false);
            new AdminPortal().setVisible(true);
        }
        else if (ID_type.equals("D"))
        {
            this.setVisible(false);
            new DoctorPortal().setVisible(true);
        }
        else
        {
            lbl_outputStatus.setText("Portal for this user type is currently unavailable");
        }
        
    }
    
    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel lbl_outputStatus;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Pw;
    // End of variables declaration//GEN-END:variables
}
