/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Objects.Address;
import Objects.DoctorRating;
import Objects.DoctorRatingsDatabase;
import Objects.UserDatabase;
import doctors.surgery.users.Doctor;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author jwood20
 */
public class PatientPortal extends javax.swing.JFrame {

    public UserDatabase userData = UserDatabase.getInstanceOfDatabase();
    public DoctorRatingsDatabase ratingDatabase = DoctorRatingsDatabase.getInstanceOfDatabase();
    ArrayList<DoctorRating> docsRatings;
    DefaultListModel<String> docListModel;
    /**
     * Creates new form PatientPortal
     */
    public PatientPortal() {
        initComponents();
        
        lbl_loggedInName.setText(userData.loggedInUser.getSurname());
        System.out.println(userData.loggedInUser.getSurname());
        
        
        
        //fill docNameList
        docListModel = new DefaultListModel<>();
        
        System.out.println(userData.getNumberOfRoles("Doctor"));
        for(Integer i = 0; i < userData.getNumberOfRoles("Doctor") ; i ++)
        {
            String tempString;
            tempString = userData.getListOfRoles("Doctor").get(i).getSurname();
            docListModel.addElement(tempString);
        }
        
        jList_Docs.setModel(docListModel);
        jList_Docs1.setModel(docListModel);
        
        
        updateRatingsList();
        updateComments();
    }

    public void updateRatingsList()
    {
        String currentDoc = "";
        if(jList_Docs.getSelectedIndex()>= 0)
        {
            currentDoc = jList_Docs.getSelectedValue();
        }
        else
        {
            currentDoc = docListModel.get(0);
        }
        
        docsRatings = ratingDatabase.getDocsRatingsSurname(currentDoc);
        
        DefaultListModel<String> docsListModel = new DefaultListModel<>();
        
        for(Integer i = 0; i < docsRatings.size() ; i++)
        {
            String listText;
            listText = docsRatings.get(i).getRateOutOfFive() + "/5 stars";
            docsListModel.addElement(listText);
        }
        jList_ratings.setModel(docsListModel);
        
        updateComments();
    }

    public void updateComments()
    {
        String newText = "";
        if(jList_ratings.getSelectedIndex() < 0)
        {
            newText = docsRatings.get(0).getComments();
        }
        else
        {
            newText = docsRatings.get(jList_ratings.getSelectedIndex()).getComments();
        }
        
        txt_comments.setText(newText);
    }
    
    public void submitRating()
    {
        Doctor doctor = ((Doctor)userData.findDoctor(jList_Docs1.getSelectedValue()));
        Integer num = Integer.parseInt(txt_newrateNum.getText());
        String comments = txt_newRateComment.getText();
        
        DoctorRating newRate = new DoctorRating(doctor, num, comments);
        ratingDatabase.addNewRating(newRate);
        updateRatingsList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_ratings = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Docs = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_comments = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        lbl_loggedInName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_Docs1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        txt_newrateNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_newRateComment = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel9.setText("DOCTOR PORTAL ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Pick a Rating to View");

        jList_ratings.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jList_ratings.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_ratings.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_ratingsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_ratings);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Select a Doctor to view their ratings");

        jList_Docs.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jList_Docs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_Docs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_DocsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList_Docs);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Comments");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel5.setText("LEAVE A RATING FOR YOUR DOCTOR");

        txt_comments.setEditable(false);
        txt_comments.setColumns(20);
        txt_comments.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txt_comments.setRows(5);
        jScrollPane2.setViewportView(txt_comments);

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel10.setText("PATIENT PORTAL ");

        lbl_loggedInName.setText("jLabel1");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel6.setText("VIEW DOCTOR RATINGS FOR YOUR SURGERY ");

        jList_Docs1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jList_Docs1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_Docs1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_Docs1ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList_Docs1);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Leave a comment ");

        txt_newrateNum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Select which Doctor to rate");

        txt_newRateComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newRateCommentActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setText("Give a rating out of 5");

        jButton1.setText("Submit Rating");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel4)
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_loggedInName)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txt_newrateNum, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_newRateComment, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel11)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7)))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_loggedInName)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10))
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txt_newrateNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_newRateComment, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_ratingsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_ratingsValueChanged
        // TODO add your handling code here:
        
        updateComments();
    }//GEN-LAST:event_jList_ratingsValueChanged

    private void jList_DocsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_DocsValueChanged
        // TODO add your handling code here:
        //CHANGE WHICH DOCTORS RATINGS TO VIEW

        updateRatingsList();
        updateComments();
    }//GEN-LAST:event_jList_DocsValueChanged

    private void jList_Docs1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_Docs1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList_Docs1ValueChanged

    private void txt_newRateCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newRateCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newRateCommentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            submitRating();
        // TODO add your handling code here:
        System.out.println("Buttonpressed");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList_Docs;
    private javax.swing.JList<String> jList_Docs1;
    private javax.swing.JList<String> jList_ratings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_loggedInName;
    private javax.swing.JTextArea txt_comments;
    private javax.swing.JTextField txt_newRateComment;
    private javax.swing.JTextField txt_newrateNum;
    // End of variables declaration//GEN-END:variables
}
