/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Objects.DoctorRating;
import Objects.DoctorRatingsDatabase;
import Objects.UserDatabase;
import doctors.surgery.users.Doctor;
import javax.swing.DefaultListModel;

/**
 *
 * @author jwood20
 */
public class ViewRatings extends javax.swing.JFrame {

    
    DoctorRatingsDatabase ratingDatabase = DoctorRatingsDatabase.getInstanceOfDatabase();
    UserDatabase userData = UserDatabase.getInstanceOfDatabase();
    /**
     * Creates new form ViewRatings
     */
    public ViewRatings() {
        initComponents();
        jList_ratings.removeAll();
        
        //populate with DOCS
        Doctor testDoc1 = new Doctor("Bowditch");
        Doctor testDoc2 = new Doctor("Smith");
        Doctor testDoc3 = new Doctor("Jones");
        
        userData.addUser(testDoc1);
        userData.addUser(testDoc2);
        userData.addUser(testDoc3);
        
        DefaultListModel<String> docListModel = new DefaultListModel<>();
        
        for(Integer i = 0; i < userData.getNumberOfRoles("Doctor") ; i ++)
        {
            String tempString;
            tempString = "Dr. " + userData.getListOfRoles("Doctor").get(i).getSurname();
            docListModel.addElement(tempString);
        }
        
        jList_Docs.setModel(docListModel);
        
        //populate with ratings for docs
        //make some ratings
        DoctorRating testRate = new DoctorRating();
        DoctorRating testRate2 = new DoctorRating();
        ratingDatabase.addNewRating(testRate);
        ratingDatabase.addNewRating(testRate2);
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        
        for(Integer i = 0; i < ratingDatabase.allRatings.size() ; i++)
        {
            String listText;
            listText = "Doctor " + ratingDatabase.allRatings.get(i).getDoctor().getSurname() + " : " + 
                    ratingDatabase.allRatings.get(i).getRateOutOfFive() + "/5 stars";
            listModel.addElement(listText);
        }
        jList_ratings.setModel(listModel);
        
    }
    
    public void updateRatingsList(String currentDoc)
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_ratings = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_comments = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Docs = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("VIEW DOCTOR RATINGS FOR YOUR SURGERY ");

        jScrollPane1.setViewportView(jList_ratings);

        txt_comments.setColumns(20);
        txt_comments.setRows(5);
        jScrollPane2.setViewportView(txt_comments);

        jList_Docs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList_Docs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(366, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRatings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRatings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRatings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRatings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRatings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList_Docs;
    private javax.swing.JList<String> jList_ratings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txt_comments;
    // End of variables declaration//GEN-END:variables
}
